default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: prototype_development

test:
  <<: *default
  database: prototype_test


production:
  <<: *default
  database: prototype_production
  username: prototype
  password: <%= ENV["PROTOTYPE2_DATABASE_PASSWORD"] %>
